name: pr_validation

on:
  push:
    branches:
      - master
      - dev
      - main
  pull_request:
    branches:
      - master
      - dev
      - main

jobs:
  test:
    name: Test-${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
          fetch-depth: 0

      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v4.0.0
        with:
          global-json-file: "./src/global.json"

      - name: "Update release notes"
        shell: pwsh
        run: |
          ./build.ps1

      - name: "dotnet build"
        run: dotnet build -c Release ./src/Reactive.Streams.sln

      # .NET Framework tests can't run reliably on Linux, so we only do .NET 6

      - name: "dotnet test"
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            dotnet test -c Release --no-build --framework net6.0 ./src/Reactive.Streams.sln
          else
            dotnet test -c Release --no-build ./src/Reactive.Streams.sln
          fi

      - name: "dotnet pack"
        run: dotnet pack -c Release --no-build